// src/constants/workoutData.ts
const workoutData = [
  {
    value: "CARDIO",
    title: "Cardio",
    children: [
      { value: "Running", title: "Running" },
      { value: "Walking", title: "Walking" },
      { value: "Stairmaster", title: "Stairmaster" },
      { value: "Stationary Bike", title: "Stationary Bike" },
    ],
  },
  {
    value: "STRENGTH",
    title: "Strength Training",
    children: [
      { value: "Bodybuilding", title: "Bodybuilding" },
      { value: "Circuit", title: "Circuit" },
      { value: "Powerlifting", title: "Powerlifting" },
    ],
    muscleGroups: [
      {
        name: "Legs",
        exercises: [
          "Squats",
          "Lunges",
          "Leg Press",
          "Hamstring Curl",
          "Romanian Deadlift (RDL)",
          "Bulgarian Split Squat",
          "Step-Ups",
          "Calf Raises",
          "Leg Extension",
          "Sumo Squat",
          "Glute Bridge",
          "Hip Thrust",
          "Goblet Squat",
          "Front Squat",
          "Box Jump",
          "Hack Squat",
          "Pistol Squat",
          "Wall Sit",
          "Reverse Lunge",
          "Donkey Kick",
        ],
      },
      {
        name: "Arms",
        exercises: [
          "Bicep Curl",
          "Hammer Curl",
          "Concentration Curl",
          "Preacher Curl",
          "Tricep Pushdown",
          "Overhead Tricep Extension",
          "Dips",
          "Close-Grip Bench Press",
          "Skull Crusher",
          "Reverse Curl",
        ],
      },
      {
        name: "Back",
        exercises: [
          "Pull-Up",
          "Chin-Up",
          "Deadlift",
          "Bent-Over Row",
          "Lat Pulldown",
          "Single-Arm Dumbbell Row",
          "T-Bar Row",
          "Seated Cable Row",
          "Superman Exercise",
        ],
      },
      {
        name: "Chest",
        exercises: [
          "Bench Press",
          "Incline Bench Press",
          "Decline Bench Press",
          "Chest Fly",
          "Push-Up",
          "Incline Push-Up",
          "Cable Cross-Over",
          "Dumbbell Pullover",
          "Pec Deck",
        ],
      },
      {
        name: "Shoulders",
        exercises: [
          "Overhead Press",
          "Arnold Press",
          "Lateral Raise",
          "Front Raise",
          "Reverse Fly",
          "Upright Row",
          "Shrugs",
          "Face Pull",
          "Dumbbell Scaption",
          "Push Press",
        ],
      },
      {
        name: "Core",
        exercises: [
          "Plank",
          "Side Plank",
          "Russian Twist",
          "Bicycle Crunch",
          "Hanging Leg Raise",
          "Mountain Climbers",
          "V-Ups",
          "Sit-Up",
          "Ab Rollout",
          "Flutter Kicks",
        ],
      },
    ],
  },
  {
    value: "CLASSES",
    title: "Classes",
    children: [
      { value: "Dancing", title: "Dancing" },
      { value: "Yoga", title: "Yoga" },
      { value: "Pilates", title: "Pilates" },
      { value: "Spin", title: "Spin" },
      { value: "Barre", title: "Barre" },
      { value: "Zumba", title: "Zumba" },
    ],
  },
  {
    value: "SPORTS",
    title: "Sports",
    children: [
      { value: "Basketball", title: "Basketball" },
      { value: "Soccer", title: "Soccer" },
      { value: "Tennis", title: "Tennis" },
      { value: "Volleyball", title: "Volleyball" },
      { value: "Baseball", title: "Baseball" },
      { value: "Football", title: "Football" },
      { value: "Golf", title: "Golf" },
      { value: "Hockey", title: "Hockey" },
      { value: "Lacrosse", title: "Lacrosse" },
      { value: "Rugby", title: "Rugby" },
      { value: "Softball", title: "Softball" },
      { value: "Track", title: "Track" },
      { value: "Wrestling", title: "Wrestling" },
      { value: "Martialarts", title: "Martial Arts" },
      { value: "Boxing", title: "Boxing" },
      { value: "MMA", title: "MMA" },
      { value: "Judo", title: "Judo" },
      { value: "Karate", title: "Karate" },
      { value: "Taekwondo", title: "Taekwondo" },
      { value: "Swimming", title: "Swimming" },
      { value: "Cycling", title: "Cycling" },
      { value: "Muaithai", title: "Muaithai" },
    ],
  },
  {
    value: "OTHER",
    title: "Other",
    children: [
      { value: "Calisthenics", title: "Calisthenics" },
      { value: "Hiking", title: "Hiking" },
      { value: "Rock Climbing", title: "Rock Climbing" },
      { value: "Crossfit", title: "Crossfit" },
    ],
  },
];

export default workoutData;
